### ISSUE TITLE
Unable to install Azure pipelines

### ISSUE THREAD

**Issue by jaraco** [pmxbot/pmxbot#86]
I'm moving the projects I maintain from Travis to [Azure](https://dev.azure.com/jaraco/pmxbot), but because I'm not admin on this project, I'm unable to install the necessary GitHub hook.

![image](https://user-images.githubusercontent.com/308610/74015288-516be380-495e-11ea-91d4-023d10e1df27.png)

[Learn more links here](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#integrate-using-the-github-app), which describes their recommendations and details on how permissions might be set up.

I'd be happy for YouGov to own an organization in Azure pipelines, but I'm guessing that's not an interesting proposition, so I propose instead you grant me access to the YouGov organization or transfer some of these projects over to my personal org (/jaraco).

Let me know what you think.

**Comment by lbolla** [comment]
Travis seems to be working fine (https://travis-ci.org/yougov/pmxbot). What is the reason to change it?
I will bring this question up internally and let you know!

**Comment by lbolla** [comment]
What about we create a new organization just for pmxbot? e.g. https://github.com/pmxbot
This seems the preferred solution by other developers I asked.

**Comment by jaraco** [comment]
> What is the reason to change it?

Good question. I've been migrating away from Travis for several reasons:

- limited support for other platforms (macOS, Windows)
- broken IPv6 implementation
- slow adoption of newer Linux platforms/containers
- broken support for secrets (necessary for automated releases)
- only per-repository secrets (no organization-level secret management)

The Azure Pipelines addresses all of these concerns with few downsides.

> What about we create a new organization just for pmxbot?

Yes, I was considering proposing the same thing.

I've created the organization and invited you as an Owner.

In addition to this project, would you transfer the other pmxbot repos?

- pmxbot.rss
- motivation
- excuses
- popquotes
- pmxbot.saysomething
- chucknorris
- pmxbot.nsfw
- pmxbot.logging

**Comment by lbolla** [comment]
All above repos moved to @pmxbot.

**Comment by jaraco** [comment]
Thanks lbolla. Tagged commits are now [mechanically released by Azure](https://dev.azure.com/pmxbot/pmxbot/_build/results?buildId=3&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=b2856b68-7f1b-5690-c0cb-cbdf6a32daf7).
