### ISSUE TITLE
Only use backports when needed

### ISSUE THREAD

**Issue by toddrme2178** [pmxbot/pmxbot#87]
Currently pmxbot uses several backports packages:

- backports.method_request
- backports.unittest_mock
- importlib-metadata
- importlib_resources

These are all built-in for more recent versions of python.  Would it be possible to only pull these in for versions of python that really need them, rather than depending on them even when they aren't really needed?

For `backports.method_request` and `backports.unittest_mock`, these could be eliminated entirely by setting the minimum python version to 3.4 (or 3.5, which many other packages are doing).

**Comment by jaraco** [comment]
Sounds good to me. The minimum supported Python version is 3.6, so happy to accept PRs to remove the cruft.

**Comment by jaraco** [comment]
I've removed reliance on the two `backports.` modules.

Regarding the importlib backports, I've refreshed the usage on those, so they're still required for Pythons earlier than 3.9 or 3.10, so the backports will be necessary for some time. Therefore, I'm closing this as good enough.
